[workspace]

members = [
    "contracts/add-associated-key",
    "contracts/remove-associated-key",
    "contracts/update-associated-key",
    "contracts/authorized-keys"]

[profile.release]
lto = true 