[package]
name = "remove-associated-key"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "remove_associated_key"
path = "src/main.rs"
bench = false
doctest = false
test = false

[dependencies]
casper-contract = "1.4.4"
casper-types = "1.5.0"
